#!/usr/bin/env bash
set -euo pipefail

manifest_file="${1:-projects.env}"
output_file="${2:-docker-compose.projects.yml}"
service_name="${COMPOSE_SERVICE_NAME:-opencode}"
workspace_root="${WORKSPACE_ROOT:-/workspace}"

trim() {
  local value="$1"
  value="${value#"${value%%[![:space:]]*}"}"
  value="${value%"${value##*[![:space:]]}"}"
  printf '%s' "$value"
}

escape_yaml_double_quoted() {
  local value="$1"
  value="${value//\\/\\\\}"
  value="${value//\"/\\\"}"
  printf '%s' "$value"
}

resolve_path() {
  local raw_path="$1"
  local manifest_dir="$2"

  if [[ "$raw_path" == ~* ]]; then
    raw_path="${HOME}${raw_path#\~}"
  fi

  if [[ "$raw_path" != /* ]]; then
    raw_path="$manifest_dir/$raw_path"
  fi

  if [[ ! -d "$raw_path" ]]; then
    return 1
  fi

  (
    cd "$raw_path"
    pwd
  )
}

if [[ ! -f "$manifest_file" ]]; then
  echo "Manifest not found: $manifest_file" >&2
  echo "Create it from projects.env.example first." >&2
  exit 1
fi

manifest_dir="$(cd "$(dirname "$manifest_file")" && pwd)"

declare -a mounts=()
seen_names=""
line_number=0

while IFS= read -r raw_line || [[ -n "$raw_line" ]]; do
  line_number=$((line_number + 1))
  line="$(trim "$raw_line")"

  if [[ -z "$line" || "${line:0:1}" == "#" ]]; then
    continue
  fi

  if [[ "$line" != *"="* ]]; then
    echo "Invalid entry at line $line_number: missing '='" >&2
    exit 1
  fi

  name="$(trim "${line%%=*}")"
  host_path_raw="$(trim "${line#*=}")"

  if [[ -z "$name" || -z "$host_path_raw" ]]; then
    echo "Invalid entry at line $line_number: name and path are required" >&2
    exit 1
  fi

  if [[ ! "$name" =~ ^[a-zA-Z0-9._-]+$ ]]; then
    echo "Invalid project name '$name' at line $line_number" >&2
    echo "Allowed characters: letters, numbers, dot, underscore, hyphen" >&2
    exit 1
  fi

  if echo "$seen_names" | grep -qxF "$name"; then
    echo "Duplicate project name '$name' at line $line_number" >&2
    exit 1
  fi
  if [[ -z "$seen_names" ]]; then
    seen_names="$name"
  else
    seen_names="$seen_names"$'\n'"$name"
  fi

  if ! host_path="$(resolve_path "$host_path_raw" "$manifest_dir")"; then
    echo "Host path does not exist for '$name': $host_path_raw" >&2
    exit 1
  fi

  mounts+=("$host_path:$workspace_root/$name")
done < "$manifest_file"

{
  echo "# Generated by scripts/generate-compose-project-mounts.sh"
  echo "# Source manifest: $manifest_file"
  echo "services:"
  echo "  $service_name:"
  if [[ ${#mounts[@]} -eq 0 ]]; then
    echo "    volumes: []"
  else
    echo "    volumes:"
    for mount in "${mounts[@]}"; do
      escaped_mount="$(escape_yaml_double_quoted "$mount")"
      echo "      - \"$escaped_mount\""
    done
  fi
} > "$output_file"

if [[ ${#mounts[@]} -eq 0 ]]; then
  echo "Warning: no project mounts generated." >&2
  echo "Add entries to $manifest_file and re-run." >&2
fi
echo "Generated $output_file with ${#mounts[@]} project mount(s)."
